SELECT DISTINCT JOB
FROM SCOTT.EMP;

SELECT DISTINCT DEPTNO
FROM SCOTT.EMP;

SELECT DISTINCT JOB, DEPTNO
FROM SCOTT.EMP;

SELECT DISTINCT DEPTNO, SAL
FROM SCOTT.EMP;

SELECT DISTINCT JOB, SAL
FROM SCOTT.EMP;

SELECT DISTINCT HIREDATE
FROM SCOTT.EMP;

SELECT DISTINCT JOB, SAL, DEPTNO
FROM SCOTT.EMP;

SELECT DISTINCT HIREDATE, JOB
FROM SCOTT.EMP;

SELECT DISTINCT SAL, DEPTNO, JOB, HIREDATE
FROM SCOTT.EMP;

SELECT DISTINCT *
FROM SCOTT.EMP;