SELECT
    'MR. '
    || ENAME
    || ' YOU HIRED ON '
    || HIREDATE
    || ' IN DEPTNO'
    || DEPTNO
FROM
    SCOTT.EMP;

SET PAGES 100 LINES 100

SELECT 'HEY! '||ENAME|| ' YOUR WORKIN AS '||JOB|| ' IN DEPTNO '||DEPTNO
FROM SCOTT.EMP;

SELECT 'OYE! '||ENAME|| ' YOUR SALARY IS RS. '||SAL|| ' AND COMMISION IS '||COMM
FROM SCOTT.EMP;

SELECT 'HEY DONKEY! '||ENAME|| ' WORK MORE AND GIVR ME YOUR ANAUAL SALARY IN ONE SHORT THAT IS '||(SAL*12)
FROM SCOTT.EMP;

SELECT 'SORRY! '||ENAME|| ' YOUR SAL IS '||SAL|| ' AND WE ARE DEDUCTING 100 RPS IN IT FOR THAT YOU WILL GET JUST '||(SAL - 100)
FROM SCOTT.EMP;

SELECT 'HI! '||ENAME|| ' YOUR DESIGNATION IS '||JOB|| ' THAT TO IN DEPTNO '  ||DEPTNO
FROM SCOTT.EMP;

SELECT 'HELLO! '||ENAME|| ' YOUR EMP ID IS '||EMPNO|| ' AND MANAGER ID IS '||MGR
FROM SCOTT.EMP;

SELECT ENAME|| ' IS VERY KIND HEARTED AND WE NEED TO APPRICIATE THAT'
FROM SCOTT.EMP;

SELECT 'MR. '||ENAME|| ' YOUR SALARY IS RS. '||SAL|| ' AND HALFTERM IS '||(SAL*6)
FROM SCOTT.EMP;

SELECT 'HEY! '||ENAME|| ' YOUR SALARY IS RS. '||SAL|| ' AND YOU GOT 3000 RPS HIKE SO YOU WILL GET RS. '||(SAL + 3000)
FROM SCOTT.EMP;