SELECT ENAME
FROM SCOTT.EMP
WHERE HIREDATE BETWEEN '01-JAN-82' AND '31-DEC-87';

SELECT *
FROM SCOTT.EMP
WHERE DEPTNO NOT IN (10, 20);

SELECT *
FROM SCOTT.EMP
WHERE JOB NOT IN ('PRESIDENT', 'MANAGER');

SELECT ENAME
FROM SCOTT.EMP
WHERE DEPTNO IN (10, 20) AND
        JOB NOT IN ('CLERK', 'SALESMAN');

SELECT *
FROM SCOTT.EMP
WHERE HIREDATE NOT BETWEEN '01-JAN-81' AND '31-DEC-81';

SELECT ENAME
FROM SCOTT.EMP
WHERE HIREDATE BETWEEN '01-JAN-81' AND '31-DEC-86' AND
        HIREDATE NOT LIKE '%82';

SELECT ENAME
FROM SCOTT.EMP
WHERE JOB IN ('PRESIDENT', 'ANALYST') AND
        DEPTNO IN (10, 20);

SELECT *
FROM SCOTT.EMP
WHERE HIREDATE LIKE '%87';

SELECT ENAME
FROM SCOTT.EMP
WHERE JOB IN ('MANAGER', 'ANALYST', 'PRESIDENT') AND
        DEPTNO IN (10, 20) AND 
        SAL > 2900;

SELECT ENAME
FROM SCOTT.EMP
WHERE JOB IN ('SALESMAN', 'MANAGER') AND
        DEPTNO IN (10, 30) AND 
        HIREDATE > '31-DEC-80' AND 
        COMM = 1400;

SELECT ENAME
FROM SCOTT.EMP
WHERE JOB IN ('PRESIDENT', 'SALESMAN', 'CLERK') AND
        DEPTNO IN (10, 30) AND 
        HIREDATE BETWEEN '01-JAN-81' AND '31-DEC-82' AND
        SAL >= 3000;

SELECT EMP.*, SAL*12 ANN_SAL
FROM SCOTT.EMP
WHERE JOB IN ('MANAGER', 'PRESIDENT') AND
        DEPTNO IN (10, 30) AND
        HIREDATE LIKE '%81'  AND --BETWEEN '01-JAN-81' AND '31-DEC-81'
        SAL = 2850;