SELECT MIN(SAL), DEPTNO
FROM SCOTT.EMP
GROUP BY DEPTNO;

SELECT AVG(SAL), JOB 
FROM SCOTT.EMP
GROUP BY JOB;

SELECT COUNT(*), DEPTNO
FROM SCOTT.EMP
WHERE SAL > 2000
GROUP BY DEPTNO;

SELECT COUNT(*), DEPTNO
FROM SCOTT.EMP
WHERE JOB != 'PRESIDENT'
GROUP BY DEPTNO;

SELECT COUNT(*), DEPTNO
FROM SCOTT.EMP
WHERE JOB = 'MANAGER'
GROUP BY DEPTNO;

SELECT AVG(SAL), JOB
FROM SCOTT.EMP
WHERE DEPTNO != 20
GROUP BY JOB;

SELECT COUNT(*), JOB
FROM SCOTT.EMP
WHERE ENAME LIKE '%A%'
GROUP BY JOB;

SELECT COUNT(*), DEPTNO
FROM SCOTT.EMP
WHERE JOB = 'CLERK'
GROUP BY DEPTNO;

SELECT COUNT(*), DEPTNO
FROM SCOTT.EMP
WHERE HIREDATE LIKE '%81'
GROUP BY DEPTNO;

SELECT COUNT(*),DEPTNO
FROM SCOTT.EMP
WHERE SAL < 1000
GROUP BY DEPTNO;

SELECT COUNT(*),DEPTNO
FROM SCOTT.EMP
WHERE SAL = 3000
GROUP BY DEPTNO;

SELECT MAX(SAL), DEPTNO
FROM SCOTT.EMP
WHERE JOB = 'CLERK'
GROUP BY DEPTNO;

SELECT COUNT(*), JOB 
FROM SCOTT.EMP
WHERE HIREDATE LIKE '%FEB%' -- '%FEB' ❌
GROUP BY JOB;

SELECT COUNT(*), DEPTNO
FROM SCOTT.EMP
WHERE JOB IN ('PRESIDENT', 'ANALYST') AND
            SAL > 2000
GROUP BY DEPTNO;

SELECT COUNT(*), DEPTNO
FROM SCOTT.EMP
WHERE JOB != 'PRESIDENT'
GROUP BY DEPTNO;

SELECT SUM(SAL), JOB
FROM SCOTT.EMP
GROUP BY JOB;

SELECT AVG(SAL), DEPTNO
FROM SCOTT.EMP
WHERE DEPTNO != 20
GROUP BY DEPTNO;

SELECT COUNT(*), JOB
FROM SCOTT.EMP
WHERE ENAME LIKE '%A%'
GROUP BY JOB;

SELECT COUNT(*), AVG(SAL), DEPTNO
FROM SCOTT.EMP
WHERE SAL > 2000
GROUP BY DEPTNO;

SELECT SUM(SAL), DEPTNO
FROM SCOTT.EMP
WHERE JOB = 'SALESMAN'
GROUP BY DEPTNO;

SELECT COUNT(*), SUM(SAL), JOB
FROM SCOTT.EMP
GROUP BY JOB;

SELECT COUNT(*), SAL 
FROM SCOTT.EMP
GROUP BY SAL;

SELECT COUNT(*), DEPTNO 
FROM SCOTT.EMP
-- WHERE COUNT(DEPTNO) >= 2
GROUP BY DEPTNO ;

SELECT AVG(SAL), MAX(SAL), MIN(SAL), JOB
FROM SCOTT.EMP
WHERE HIREDATE > '31-DEC-80'
GROUP BY JOB;

SELECT COUNT(*), DEPTNO
FROM SCOTT.EMP
WHERE SAL > 2000 AND
         HIREDATE LIKE '%87'
GROUP BY DEPTNO;