SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE JOB = 'PRESIDENT');

SELECT ENAME
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE DNAME = 'ACCOUNTING');

SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE LOC = 'CHICAGO');

SELECT *
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE DNAME = 'SALES');

SELECT EMP.*, SAL*12
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE LOC = 'NEW YORK');

SELECT ENAME
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE DNAME = 'OPERATIONS');

SELECT ENAME
FROM SCOTT.EMP
WHERE   SAL > ( SELECT SAL
                FROM SCOTT.EMP
                WHERE ENAME = 'SCOTT' )AND
        DEPTNO IN (SELECT DEPTNO
                    FROM SCOTT.DEPT
                    WHERE DNAME = 'ACCOUNTING');

SELECT *
FROM SCOTT.EMP
WHERE JOB = 'MANAGER' AND 
                DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE LOC = 'CHICAGO');

SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE   SAL > (SELECT SAL
                FROM SCOTT.EMP
                WHERE ENAME = 'KING') AND
        DEPTNO IN (SELECT DEPTNO
                   FROM SCOTT.DEPT
                   WHERE DNAME = 'ACCOUNTING');

SELECT *
FROM SCOTT.EMP
WHERE   JOB = 'SALESMAN' AND
        DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE DNAME = 'SALES');

SELECT ENAME, SAL, JOB, HIREDATE
FROM SCOTT.EMP
WHERE   DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE DNAME = 'OPERATION') AND
        HIREDATE < (SELECT HIREDATE 
                    FROM SCOTT.EMP
                    WHERE ENAME = 'KING');

SELECT ENAME 
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                    FROM SCOTT.DEPT
                    WHERE DNAME LIKE '%S');

SELECT DNAME
FROM SCOTT.DEPT
WHERE   DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE SAL = 800);

SELECT DNAME, LOC
FROM SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                    FROM SCOTT.EMP
                    WHERE ENAME LIKE '%A%');

SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                    FROM SCOTT.EMP
                    WHERE COMM IS NOT NULL);

SELECT LOC
FROM SCOTT.DEPT
WHERE  DEPTNO IN (SELECT DEPTNO
                    FROM SCOTT.EMP
                    WHERE (DEPTNO = 40 OR            -- OR AEGGA YA AND
                        COMM IS NOT NULL));

SELECT ENAME
FROM SCOTT.EMP
WHERE SAL IN (SELECT MAX(SAL)
            FROM SCOTT.EMP);