-- 1] WAQTD 5TH RECORD FROM EMP TABLE.
SELECT *
FROM (SELECT ROWNUM AS SLNO, EMP.*
        FROM SCOTT.EMP)
WHERE SLNO = 5;

-- 2] WAQTD ENAME, SAL FROM 7TH RECORD.
SELECT ENAME , SAL
FROM (SELECT ROWNUM AS SLNO, EMP.*
        FROM SCOTT.EMP)
WHERE SLNO = 7;

-- 3] WAQTD DETAILS OF 1ST, 3RD, 5TH, 8TH RECORD.
SELECT *
FROM (SELECT ROWNUM AS SLNO, EMP.*
        FROM SCOTT.EMP)
WHERE SLNO IN (1, 3, 5, 8 );

-- 4] WAQTD ENAME OF 8TH, 7TH & 6TH RECORD.
SELECT ENAME
FROM (SELECT ROWNUM AS SLNO, EMP.*
        FROM SCOTT.EMP)
WHERE SLNO IN (8, 7, 6);

-- 5] WAQTD DNAME OF 4TH RECORD.
SELECT DNAME
FROM (SELECT ROWNUM AS SLNO, DEPT.*
        FROM SCOTT.DEPT)
WHERE SLNO = 4;
SELECT *            -- FOR VERIFICATION
FROM SCOTT.DEPT;

-- 6] WAQTD DNAME OF 6TH RECORD IN EMP TABLE.
SELECT DNAME
FROM SCOTT.DEPT 
WHERE DEPTNO IN (SELECT DEPTNO
                FROM (SELECT ROWNUM SLNO, EMP.*
                        FROM SCOTT.EMP)
                WHERE SLNO = 6);


-- 7] WAQTD 2ND MAX SAL.
SELECT MAX(SAL)
FROM SCOTT.EMP
WHERE SAL < (SELECT MAX(SAL)
            FROM SCOTT.EMP);


-- 8] WAQTD 3RD MAX SAL USING ROWNUM❓
SELECT * 
FROM (SELECT SAL
    FROM (SELECT DISTINCT SAL
            FROM SCOTT.EMP
            ORDER BY SAL DESC)
    WHERE ROWNUM <= 3)
ORDER BY SAL ASC
FETCH FIRST 1 ROW ONLY;

SELECT *                               -- 👌
FROM (SELECT DISTINCT SAL, ROWNUM AS SLNO
        FROM ( SELECT DISTINCT SAL
                FROM SCOTT.EMP
                ORDER BY SAL DESC))
WHERE SLNO = 3;

-- 9] WAQTD ENAME WHO EARNS 4TH MIN SAL. ❓
SELECT ENAME                    -- 👍
FROM SCOTT.EMP
WHERE SAL = (SELECT SAL 
            FROM (SELECT DISTINCT SAL
                    FROM SCOTT.EMP
                    ORDER BY SAL ASC)
            OFFSET 3 ROWS FETCH NEXT 1 ROW ONLY);

SELECT ENAME                    -- GIVES SINGLE O/P 👎
FROM SCOTT.EMP
WHERE SAL IN (SELECT MIN(SAL)
            FROM (SELECT DISTINCT SAL
                    FROM SCOTT.EMP
                    WHERE ROWNUM <= 4
                    ORDER BY SAL ASC));


-- 10] WAQTD 7TH 8TH & 9TH MAX SAL.
SELECT SAL MAX_SAL
FROM (SELECT DISTINCT SAL, ROWNUM AS SLNO
    FROM ( SELECT DISTINCT SAL
            FROM SCOTT.EMP
            ORDER BY SAL DESC))
WHERE SLNO BETWEEN 7 AND 9;


-- 12] WAQTD DETAILS OF EMP WHO EARNS 10TH MAX SAL.
SELECT *
FROM (SELECT DISTINCT SAL, ROWNUM AS SLNO
    FROM ( SELECT DISTINCT SAL
            FROM SCOTT.EMP
            ORDER BY SAL DESC))
WHERE SLNO = 10;

-- 13] WAQTD LOC OF EMP WHO EARNS 2ND MIN SAL.
SELECT LOC
FROM  SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO 
                FROM SCOTT.EMP
                WHERE SAL = (SELECT SAL 
                    FROM (SELECT DISTINCT SAL
                            FROM SCOTT.EMP
                            ORDER BY SAL ASC)
            OFFSET 3 ROWS FETCH NEXT 1 ROW ONLY));

-- 15] WAQTD ENAME, SAL,COMM WHO EARNS 7TH MAX SAL.
SELECT SAL    -- "COMM": invalid identifier AND "ENAME": invalid identifier
FROM (SELECT DISTINCT SAL, ROWNUM SLNO
        FROM (SELECT DISTINCT SAL
                FROM SCOTT.EMP
                ORDER BY SAL DESC))
WHERE SLNO = 7;


-- 16] WAQTD LAST 3 RECORDS FROM EMP TABLE.
SELECT * 
FROM (SELECT * 
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE ROWNUM <= 3;

SELECT *
FROM SCOTT.EMP;

-- 17] WAQTD 7TH MIN SAL.
SELECT SAL
FROM SCOTT.EMP
WHERE SAL IN (SELECT SAL 
            FROM (SELECT DISTINCT SAL
                    FROM SCOTT.EMP
                    ORDER BY SAL ASC)
            OFFSET 8 ROWS FETCH NEXT 1 ROW ONLY);  -- 2850 BUT IN PDF 1600

-- 18] WAQTD LAST RECORD FROM EMP TABLE.
SELECT *
FROM (SELECT *
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE ROWNUM = 1;

-- 19] WAQTD LAST 5 RECORDS IN EMP TABLE.
SELECT *
FROM (SELECT *
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE ROWNUM <= 5;

-- 20] WAQTD 10TH MAX SALARY.
SELECT SAL
FROM (SELECT DISTINCT SAL, ROWNUM AS SLNO
        FROM (SELECT DISTINCT SAL
                FROM SCOTT.EMP
                ORDER BY SAL DESC    ) )
WHERE SLNO = 10;