--1) WAQTD 1 ST HALF RECORDS ?
SELECT *
FROM (SELECT *
        FROM SCOTT.EMP
        ORDER BY EMPNO )
WHERE ROWNUM <= (SELECT FLOOR(COUNT(*) / 2) 
                FROM SCOTT.EMP);

--2) WAQTD 2 ND HALF RECORDS ? 
SELECT * 
FROM (SELECT EMP.*, ROWNUM AS SLNO
    FROM (SELECT * 
            FROM SCOTT.EMP 
            ORDER BY EMPNO) EMP)
WHERE SLNO > (SELECT FLOOR(COUNT(*) / 2) 
            FROM SCOTT.EMP);

-- 3) LAST RECORD
SELECT *
FROM (SELECT *
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE ROWNUM = 1;

SELECT *
FROM SCOTT.EMP;

-- 4) 2ND LAST
SELECT *
FROM (SELECT ROWNUM SLNO, EMP.*
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE SLNO = 2;

SELECT *
FROM (SELECT *
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE ROWNUM <= 2;

-- 5) 3RD LAST
SELECT *
FROM (SELECT ROWNUM SLNO, EMP.*
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE SLNO = 3;

-- 6) 4TH LAST
SELECT *
FROM (SELECT ROWNUM SLNO, EMP.*
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE SLNO = 4;

-- 7) 5TH LAST RECORD
SELECT *
FROM (SELECT ROWNUM SLNO, EMP.*
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE SLNO = 5;

-- 8) LAST FIVE RECORD 
SELECT *
FROM (SELECT ROWNUM SLNO, EMP.*
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE SLNO <= 5;

-- 9) LAST 7 RECORD 'S
SELECT *
FROM (SELECT ROWNUM SLNO, EMP.*
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE SLNO <= 7;

-- 10) LAST 10 RECORD'S
SELECT *
FROM (SELECT ROWNUM SLNO, EMP.*
        FROM SCOTT.EMP
        ORDER BY EMPNO DESC)
WHERE SLNO <= 5;