-- 1] WAQTD NAMES OF AN EMP WHOSE NAME STARTS WITH CHARACTER 'A'.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, 1,1) = 'A';

-- 2] WAQTD NAMES OF AN EMP WHOSE DESIGNATION STARTS WITH CHARACTER 'S'
SELECT ENAME 
FROM SCOTT.EMP
WHERE SUBSTR(JOB, 1,1) = 'S';

-- 3] WAQTD DETAILS OF AN EMP WHOSE NAME ENDS WITH CHARACTER 'T'.
SELECT *
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,-1) = 'T';

-- 4] WAQTD DETAILS OF AN EMP WHOSE NAME HAS CHARACTER 'A'.
SELECT * 
FROM SCOTT.EMP
WHERE SUBSTR(ename, 1, 1) = 'A'
   OR SUBSTR(ename, 2, 1) = 'A'
   OR SUBSTR(ename, 3, 1) = 'A'
   OR SUBSTR(ename, 4, 1) = 'A'
   OR SUBSTR(ename, 5, 1) = 'A'
   OR SUBSTR(ename, 6, 1) = 'A'
   OR SUBSTR(ename, 7, 1) = 'A'
   OR SUBSTR(ename, 8, 1) = 'A'
   OR SUBSTR(ename, 9, 1) = 'A';

-- 5] WAQTD NAMES OF AN EMP WHO HAS CHARACTER 'A' IN SECOND PLACE OF HIS NAME.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,2, 1) = 'A';

-- 6] WAQTD DETAILS OF AN EMP HAVING 'A' IN SECOND LAST PLACE.
SELECT *
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,-2,1) = 'A';

-- 7] WAQTD DETAILS OF AN EMP HAVING 'S' IN THE LAST PLACE.
SELECT *
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,-1) = 'S';

-- 8] WAQTD NAMES OF AN EMP HAVING 'E' IN THE FOURTH PLACE
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,4,1) = 'E';

-- 9] WAQTD NAME OF AN EMP WHO HAVING CHARACTER 'A' IN
-- FIRST PLACE & 'S' IN THE LAST PLACE.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,1,1) = 'A' AND
        SUBSTR(ENAME,-1) = 'S';

-- 10] WAQTD NAME & SAL OF EMP'S IF THEY ARE EARNING 3 DIGIT
-- SALARY.
SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE LENGTH(SUBSTR(SAL,1)) = 3;

-- 11] WAQTD NAME & HIREDATE OF EMP IF THEY WERE HIRED IN
-- THE YEAR 82.
SELECT ename, hiredate
FROM SCOTT.EMP
WHERE SUBSTR(TO_CHAR(hiredate, 'DD-MON-YY'), 8, 2) = '82';

-- 12] WAQTD DETAILS OF AN EMP WHO HAVING CHARACTER 'A' IN
-- FIRST PLACE OR EMP'S IF THEY HAVE 'S' IN LAST PLACE
SELECT *
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,1,1) = 'A' OR
        SUBSTR(ENAME,-1) = 'S';

-- 13] WAQTD NAME OF AN EMP WHO HAVING CHARACTER 'A' IN
-- FIRST PLACE & WORKING IN DEPTNO 10 OR 20.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,1,1) = 'A' AND
        (SUBSTR(DEPTNO,1,2) = 10 OR
        SUBSTR(DEPTNO,1,2) = 20) ;

-- 14] WAQTD NAME & SALARY OF EMP IF THEY ARE EARNING 4
-- DIGIT SALARY
SELECT ENAME,SAL
FROM SCOTT.EMP
WHERE LENGTH(SUBSTR(SAL,1)) = 4;

-- 15] WAQTD NAME, HIREDATE IF THEY ARE HIRED IN THE YEAR       ❓
-- 81 & EARNING SALARY MORE THAN 2000.
SELECT ENAME, HIREDATE
FROM SCOTT.EMP
WHERE SUBSTR(TO_CHAR(hiredate, 'DD-MON-YY'), 8, 2) = '81' AND
    SAL > 2000;

-- 16] WAQTD DETAILS OF EMP'S IF THEY ARE HAVING STRING
-- 'MAN' IN THEIR JOB.

-- SELECT *
-- FROM SCOTT.EMP
-- WHERE SUBSTR(JOB,3) = 'MAN';

SELECT * 
FROM SCOTT.EMP
WHERE 
    SUBSTR(job, 1, 3) = 'MAN'
    OR SUBSTR(job, 2, 3) = 'MAN'
    OR SUBSTR(job, 3, 3) = 'MAN'
    OR SUBSTR(job, 4, 3) = 'MAN'
    OR SUBSTR(job, 5, 3) = 'MAN'
    OR SUBSTR(job, 6, 3) = 'MAN';

-- 17] WAQTD DETAILS OF AN EMP WHO HAVING CHARACTER 'A' IN
-- FIRST PLACE, 'D' IN SECOND PLACE & 'S' IN LAST PLACE.
SELECT *
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,1,1) = 'A' AND
        SUBSTR(ENAME,2,1) = 'D' AND
        SUBSTR(ENAME,-1,1) = 'S';

-- 18] WAQTD NAMES OF AN EMP WORKING IN DEPTNO 30 OR 40 &
-- EARNING MORE THAN 2000.
SELECT ENAME
FROM SCOTT.EMP
WHERE (SUBSTR(DEPTNO,1,2) = 30 OR
        SUBSTR(DEPTNO,1,2) = 40) AND
        SAL > 2000;

SELECT ENAME
FROM SCOTT.EMP
WHERE DEPTNO IN (30,40) AND
SAL > 2000;

-- 19] WAQTD DETAILS OF AN EMP WORKING AS 'SALESMAN' OR
-- 'MANAGER' IN DEPTNO 20 IN THE YEAR 83

-- 20] WAQTD DETAILS OF EMP ALONG WITH ANNUAL SALARY IF
-- THE ANNUAL SALARY IS MORE THAN RS.15000 IN DEPTNO 10 OR
-- 20 EXCEPT EMP'S HIRED IN THE YEAR 82.