-- WAQTD NAME,PHON NUMBER ALONG WITH MASK THE FIRST FOUR
-- DIGIT OF PHONE NUMBER OF STUDENT.
SELECT SNAME, PHNO, LPAD(SUBSTR(PHNO,-4),LENGTH(PHNO),'*') AS MASKED_PHNO
FROM STUD;

-- WAQTD MASK THE FIRST SEVEN DIGITS OF BANK ACCOUNT NUMBER.
SELECT '37935026762',LPAD(SUBSTR('37935026762',-4),LENGTH('37935026762'),'*') AS "MASKEDACCOUNTNUM"
FROM DUAL;

-- WAQTD MASK THE FIRST FOUR DIGITS AND LAST FOUR DIGITS OF
-- AADHAR NUMBER.
SELECT '1236549874','****'||SUBSTR('1236549874',-8,4)||'****' AS "MASKED AADHAR"
FROM DUAL;

-- REMOVE THE FIRST “A” FROM NAME OF ALL EMPLOYEES.
SELECT ENAME,
SUBSTR(ENAME,1,INSTR(ENAME,'A')-1)||SUBSTR(ENAME,INSTR(ENAME,'A')+1) AS RESULT 
FROM SCOTT.EMP;

-- REMOVE THE SECOND “A” FROM NAME OF ALL EMPLOYEES.
SELECT ENAME, 
SUBSTR(ENAME,1,INSTR(ENAME,'A',1,2)-1)||SUBSTR(ENAME,INSTR(ENAME,'A',1,2)+1) AS RESULT
FROM SCOTT.EMP;

-- REMOVE THE FIRST “L” FROM NAME OF ALL EMPLOYEES.
SELECT ENAME, 
SUBSTR(ENAME,1, INSTR(ENAME,'L')-1) ||SUBSTR(ENAME, INSTR(ENAME,'L')+1) AS RESULT
FROM SCOTT.EMP;

-- REMOVE THE SECOND “L” FROM NAME OF ALL EMPLOYEES.
SELECT ENAME, 
SUBSTR(ENAME,1, INSTR(ENAME,'L', 1,2)-1)||SUBSTR(ENAME, INSTR(ENAME,'L',1,2)+1) AS OP
FROM SCOTT.EMP;

-- REMOVE THE FIRST “R” FROM NAME OF ALL EMPLOYEES.
SELECT ENAME,
SUBSTR(ENAME,1,INSTR(ENAME,'R')-1) || SUBSTR(ENAME,INSTR(ENAME,'R')+1) AS RESULT
FROM SCOTT.EMP;

--9 REMOVE THE SECOND “R” FROM NAME OF ALL EMPLOYEES.
SELECT ENAME,
SUBSTR(ENAME,1,INSTR(ENAME,'R',1,2)-1) || SUBSTR(ENAME,INSTR(ENAME,'R',1,2)+1) AS RESULT
FROM SCOTT.EMP;