--1) REMOVE 1ST R?❓
SELECT REPLACE(SUBSTR(ENAME,1,INSTR(ENAME,'R',1)),'R') || SUBSTR(ENAME,1,INSTR(ENAME,'R',1)+1)
FROM SCOTT.EMP;

-- 2) REMOVE 2ND R?❓
SELECT SUBSTR(ENAME,1,INSTR(ENAME,'R,1')) || REPLACE(SUBSTR(ENAME,1,INSTR(ENAME, 'R', 1)+1), 'R')
FROM SCOTT.EMP;

--3 EMPS HIRED ON LEAP YEAR
SELECT *
FROM SCOTT.EMP
WHERE (MOD(TO_CHAR(HIREDATE,'YYYY'), 4) = 0 AND
        MOD(TO_CHAR(HIREDATE,'YYYY'),100) !=0) OR
        MOD(TO_CHAR(HIREDATE,'YYYY'), 400) = 0;

-- 1] WAQTD NAMES OF ALL THE EMP’S WHOSE NAME STARTS WITH CHAR ‘A’.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,1,1) = 'A';

-- 2] WAQTD NAME AND DESIGNATION OF THE EMP WHOSE NAME
-- ENDS WITH CHAR ‘E’.
SELECT ENAME, JOB
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, -1,1) = 'E';

-- 3] WAQTD NAMES OF EMP’S WHOSE NAME IS HAVING EXACTLY 4 CHARACTERS
SELECT ENAME
FROM SCOTT.EMP
WHERE LENGTH(ENAME) = 4;

-- 4] WAQTD DETAILS OF THE EMP’S WHOSE DESIGNATION
-- HAVING CHAR ‘K’ IN THE LAST .
SELECT *
FROM SCOTT.EMP
WHERE SUBSTR(JOB, -1,1) = 'K';

-- 5] WAQTD NAMES OF EMP’S WHOSE NAME HAVING CHAR ‘C’ IN
-- THE 2ND PLACE.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, 2,1) = 'C';

-- 6] WAQTD NAMES OF EMP’S WHOSE NAME HAVING CHAT 4TH CHAR M.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, 4,1) = 'M';

-- 7] WAQTD NAMES OF EMP’S IN LOWER CASE WHOSE NAME IS
-- HAVING STRING ‘ER’ AT THE LAST .
SELECT LOWER(ENAME)
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, -2,2) = 'ER';

-- 8] WAQTD NAMES OF EMP’S IN UPPER CASE IF HIS
-- DESIGNATION HAVING STRING ‘DEN’ FROM 6TH PLACE.
SELECT UPPER(ENAME)
FROM SCOTT.EMP
WHERE SUBSTR(JOB, 6,3) = 'DEN';

-- 9] WAQTD NAMES ONLY 1ST CHAR IN CAPITAL IF THE NAME IS
-- HAVING CHAR ‘I’ IN THE 5TH LAST CHAR.
SELECT INITCAP(ENAME)
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,5,1)= 'I';

-- 10] WAQTD NAMES OF EMP’S ALONG WITH LAST 3 CHAR’S OF
-- THE NAME IF NAME ENDS WITH CHAR ‘N’ OR DESIGNATION
-- ENDS WITH CHAR ‘R’.
SELECT ENAME, SUBSTR(ENAME,-3,3)
FROM SCOTT.EMP
WHERE SUBSTR(ENAME,-1,1) = 'N' OR
        SUBSTR(JOB,-1) = 'R';

-- 11] WAQTD NAME AND JOINING DATE OF THE EMP WHOSE
-- JOINING MONTH IS STARTS WITH ‘J'                             ❓
SELECT ENAME, HIREDATE
FROM SCOTT.EMP
WHERE SUBSTR(TO_CHAR(HIREDATE, 'MONTH'),1,1) = 'J';

-- 2] WAQTD NAME IN LOWER CASE , LENGTH OF ENAME &
-- JOINING DATE OF EMP’S WHOSE JOINING YEAR ENDS WITH
-- CHAR ‘2’.
SELECT LOWER(ENAME), LENGTH(ENAME), HIREDATE
FROM SCOTT.EMP
WHERE SUBSTR(TO_CHAR(HIREDATE, 'YY'),-1,1) = 2;

-- 13] WAQTD NAMES OF EMP’S IN REVERSE IF EMP’S
-- DESIGNATION HAVING STRING ‘LYS’ FROM 4TH LAST PLACE
SELECT REVERSE(ENAME)
FROM SCOTT.EMP
WHERE SUBSTR(JOB,-4,3) = 'LYS';

-- 14] WAQTD NAMES IN LOWER CASE, DESIGNATION WITH ONLY
-- 1ST CHAR IN CAPITAL IF THE NAME HAVING EXACTLY 6 CHAR’S
SELECT LOWER(ENAME), INITCAP(JOB) 
FROM SCOTT.EMP
WHERE LENGTH(ENAME) = 6;

-- 5] WAQTD NAMES IN REVERSE IF THE NAME IS HAVING CHAR
-- ‘U’ IN THE 2ND PLACE OR THE EMP’S SALARIES 3RD CHAR IS 0
-- (ZERO).
SELECT REVERSE(ENAME)
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, 2,1) = 'U' OR
        SUBSTR(SAL, 3,1) = 0;