-- 1️⃣ CONVERSION
--1 WAQTD NAME, HIREDATE AND HIREYEAR IF EMP HIRED IN YEAR 1981
SELECT HIREDATE, TO_CHAR(HIREDATE, 'YYYY')
FROM SCOTT.EMP
WHERE TO_CHAR(HIREDATE, 'YYYY') = 1981;

--2 NAME HIREDATE AND HIREMONTH FOR THE EMPS IF THE EMP HIRED ON SEPTEMBER OR APRIL
SELECT ENAME, HIREDATE, TO_CHAR(HIREDATE,'MON')
FROM SCOTT.EMP
-- WHERE TO_CHAR(HIREDATE,'MON') IN ('SEP', 'APR');
WHERE TO_CHAR(HIREDATE,'MM') IN (9, 4);

--3 WAQTD NAME HIREEDATE, HIREDAY FOR THE EMPS IF THE EMP HIRED ON WENESDAY OR FRIDAY
SELECT ENAME , HIREDATE, TO_CHAR(HIREDATE,'DAY')
FROM SCOTT.EMP
WHERE TO_CHAR(HIREDATE,'D') IN (4, 6);

-- TO_DATE
-- 1
SELECT TO_DATE ('1999-JAN-05', 'YYYY-MM-DD')
FROM DUAL;

SELECT TO_DATE ('2005-12-12', 'YYYY-MM-DD')
FROM DUAL;

SELECT TO_DATE ('01-JULY-99', 'DD-MM-YY')
FROM DUAL;

SELECT TO_DATE ('21-JUL-2023')
FROM DUAL;

-- 2️⃣ GENERAL
--1 WAQTD TOTAL SAL OF EMPS
SELECT SAL + COMM
FROM SCOTT.EMP;

-- WITH NVL(NULL VALUE LOGIC)
SELECT SAL + NVL(COMM, 0)
FROM SCOTT.EMP;

-- NVL2
--1 WAQTD NAME & MGRID FOR ALL THE EMPS IF THE EMP IS HAVING MGRID PRINT 1 ELSE PRINT 0
SELECT ENAME, MGR, NVL2 (MGR, 1, 0) 
FROM SCOTT.EMP;

--2 WAQTD NAME & COMM FOR THE EMPS IF THE EMP IS HAVING COMM PRINT 100 ELSE PRINT 200
SELECT ENAME , NVL2(COMM, 100, 200)
FROM SCOTT.EMP;