-- 1] WAQTD DETAILS OF EMP'S HAVING 4 CHARACTERS.
SELECT *
FROM SCOTT.EMP
WHERE LENGTH(ENAME) = 4;

-- 2] WAQTD EMP'S WHOSE JOB IS HAVING 7 CHAR'S.
SELECT ENAME, JOB
FROM SCOTT.EMP
WHERE LENGTH(JOB)=7;

-- 3] WAQTD HOW MANY TIMES LETTES 'L' OCCURS IN 'LANGUAGE'.     😭
SELECT (LENGTH('LANGUAGE')-LENGTH(REPLACE('LANGUAGE','L')))/LENGTH('L') AS COUNTTPFL
FROM DUAL;

-- 4] WAQTD NAMES & DESIGNATION OF EMP'S HAVING LAST 3 CHAR'S AS
-- 'MAN'.
SELECT ENAME, JOB
FROM SCOTT.EMP
WHERE SUBSTR(JOB,-3,3)= 'MAN';

-- 5] WAQTD NUMBER OF EMP'S WHOSE JOB IS HAVING FIRST 3 CHAR'S AS 'PRE'.
SELECT COUNT(*)
FROM SCOTT.EMP
WHERE SUBSTR(JOB, 1,3) = 'PRE';

-- 6] WAQTD NUMBER OF EMP'S WHOSE JOB IS HAVING FIRST 2 CHAR'S AS 'CL'.
SELECT COUNT(*)
FROM SCOTT.EMP
WHERE SUBSTR(JOB,1,2) = 'CL';

-- 7] WAQTD ALL THE NAMES OF EMP'S HAVING EXACTLY 1 'L'.
SELECT ENAME
FROM SCOTT.EMP
WHERE INSTR(ENAME, 'L',1) != 0 AND
        INSTR(ENAME, 'L',1,2) = 0;

-- 8] WAQTD DEPT NAMES WHICH ARE HAVING CHAR 'O' IN IT.
SELECT DNAME
FROM SCOTT.DEPT
WHERE INSTR(DNAME,'O',1) !=0;

-- 9] WAQTD NUMER OF 'L' IN STRING 'HELLO'.             😏
SELECT (LENGTH('HELLO')-LENGTH(REPLACE('HELLO','L')))/LENGTH('L') AS L
FROM DUAL;

-- 10] WAQTD DETAILS OF EMP'S WHOSE JOB HAS A STRING 'MAN'
SELECT JOB
FROM SCOTT.EMP
WHERE INSTR(JOB, 'MAN',1) != 0;

-- 11] WAQTD ALL THE EMP'S WHOSE JON STARTS WITH 'MAN'.
SELECT * 
FROM SCOTT.EMP
WHERE SUBSTR(JOB, 1, 3) = 'MAN';

-- 12] WAQTD ALL THE EMP'S WHOSE JOB ENDS WITH 'MAN'.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(JOB, -3,3) = 'MAN';

-- 13] WAQTD FIRST 3 CHAR'S OF NAME IN LOWER CASE & REST EVERYTHING
-- IN UPPER CASE.
SELECT LOWER(SUBSTR(ENAME,1,3))||UPPER(SUBSTR(ENAME,3)) LOWERUPPERNAME
FROM SCOTT.EMP;

-- 14] WAQTD THE RESULT FROM EMP TABLE AS :
-- ABC IS A XYZ AND GETS A WAGES OF PQR
-- (IF EMP IS WORKING AS A CLERK AND EARNING MORE THAN 1000)
SELECT ENAME|| ' IS A ' ||JOB|| ' AND GETS A WAGES OF '||SAL
FROM SCOTT.EMP
WHERE JOB = 'CLERK' AND
        SAL > 1000;

-- 15] WAQTD NAME, HIREDATE & HIRED DAY OF EMP'S IF THEY HIRED ON 'WEDNESDAY'.
SELECT ENAME, HIREDATE, TO_CHAR(HIREDATE, 'DAY')
FROM SCOTT.EMP
WHERE TO_CHAR(HIREDATE, 'DY') = 'WED';

-- 16] WAQTD THE EMP'S WHO HIRED IN THE LEAP YEAR.
SELECT *
FROM SCOTT.EMP
WHERE (MOD(TO_CHAR(HIREDATE, 'YYYY'),4) = 0 AND
        MOD(TO_CHAR(HIREDATE, 'YYYY'),100)!=0) OR
        MOD(TO_CHAR(HIREDATE, 'YYYY'),400)=0;

-- 17] WAQTD THE EMP'S WHO NOT HIRED IN THE LEAP YEAR.
SELECT *
FROM SCOTT.EMP
WHERE NOT (MOD(TO_CHAR(HIREDATE, 'YYYY'),4) = 0 AND
        MOD(TO_CHAR(HIREDATE, 'YYYY'),100)!=0) OR
        MOD(TO_CHAR(HIREDATE, 'YYYY'),400) = 0;

-- 18] WAQTD EMP NAME IF THEY HIRED ON SUNDAY IN THE MONTH OF MAY.
SELECT ENAME
FROM SCOTT.EMP
WHERE TO_CHAR(HIREDATE, 'DY') = 'SUN' AND
        TO_CHAR(HIREDATE, 'MON') = 'MAY';

-- 19] WAQTD NAMES OF EMP'S WHOSE NAMES STARTS WITH VOWELS.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, 1,1) IN ('A','E','I','O','U');

-- 20] WAQTD NAMES OF EMP'S WHOSE NAMES STARTS WITH CONSONENTS.
SELECT ENAME
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, 1,1) NOT IN ('A','E','I','O','U');