-- 1] WAQTD THE DNAME'S IN WHICH EMP'S ARE WORKING.
SELECT DNAME 
FROM SCOTT.DEPT D
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP E
                WHERE E.DEPTNO = D.DEPTNO);

-- 2] WAQTD THE LOCATIO'S WHERE EMP'S ARE PRESENT
SELECT LOC
FROM SCOTT.DEPT D
WHERE EXISTS (SELECT DEPTNO
                FROM SCOTT.EMP E
                WHERE E.DEPTNO = D.DEPTNO);

-- 3] WAQTD THE DNAME IN WHICH EMP'S ARE NOT WORKING.
SELECT DNAME
FROM SCOTT.DEPT D
WHERE NOT EXISTS (SELECT DEPTNO
                    FROM SCOTT.EMP E
                    WHERE E.DEPTNO = D.DEPTNO);

-- 4] WAQTD THE DIFFERENT DESIGNATIONS IN WHICH EMP'S ARE WORKING
-- IN ALL THE DNAME'S OF DEPT TABLE.
SELECT DISTINCT JOB
FROM SCOTT.EMP 
WHERE EXISTS (SELECT DEPTNO
                FROM SCOTT.DEPT D
                WHERE EXISTS (SELECT DEPTNO
                                FROM SCOTT.EMP E
                                WHERE E.DEPTNO = D.DEPTNO));

-- 5] WAQTD TOTAL NUMBER OF EMP'S PRESENT IN ALL THE LOCATIONS.
SELECT COUNT(*)
FROM SCOTT.EMP E
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.DEPT D
                WHERE E.DEPTNO = D.DEPTNO);  -- GIVES THE ANSWER BUT HOW ITS CORRECT

-- 6] WAQTD 4TH MAX SALARY IN EMP TABLE.
SELECT SAL
FROM SCOTT.EMP E1
WHERE (SELECT COUNT(DISTINCT SAL)
        FROM SCOTT.EMP E2
        WHERE E1.SAL < E2.SAL) = 3;

-- 7] WAQTD 8TH MIN SAL IN EMP TABLE.
SELECT SAL
FROM SCOTT.EMP E1
WHERE (SELECT COUNT(DISTINCT SAL)
        FROM SCOTT.EMP E2
        WHERE E1.SAL > E2.SAL) = 7;

-- 8] WAQTD 1ST , 3RD AND 5TH MAX SAL.
SELECT SAL
FROM SCOTT.EMP E1
WHERE (SELECT COUNT(DISTINCT SAL)
                    FROM SCOTT.EMP E2
                    WHERE E1.SAL < E2.SAL) IN (4, 2, 0);

-- 9] WAQTD 2ND, 4TH AND 6TH MIN SAL.
SELECT SAL
FROM SCOTT.EMP E1
WHERE (SELECT COUNT(DISTINCT SAL)
        FROM SCOTT.EMP E2
        WHERE E1.SAL > E2.SAL) IN (1, 3, 5);

-- 10] WAQTD NAME OF AN EMP WHO IS EARNING 6TH MAX SALARY.
SELECT ENAME
FROM SCOTT.EMP E1
WHERE (SELECT COUNT(DISTINCT SAL)
        FROM SCOTT.EMP E2
        WHERE E1.SAL < E2.SAL) = 5;

-- 11] WAQTD DNAME OF AN EMP WHO IS EARNING 7TH MAX SAL.
SELECT DNAME
FROM SCOTT.DEPT 
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP E1
                WHERE (SELECT COUNT(DISTINCT SAL)
                        FROM SCOTT.EMP E2
                        WHERE E1.SAL < E2.SAL) = 6);

-- 12] WAQTD LOC OF AN EMP WHO IS EARNING 9TH MIN SAL.
SELECT LOC
FROM SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP E1
                WHERE (SELECT COUNT(DISTINCT SAL)
                        FROM SCOTT.EMP E2
                        WHERE E1.SAL > E2.SAL) = 8);

-- 13] WAQTD MANAGER NAME OF AN EMP WHO IS EARNING 2ND MIN SALARY.
SELECT ENAME
FROM SCOTT.EMP
WHERE EMPNO IN (SELECT MGR
                FROM SCOTT.EMP E1
                WHERE (SELECT COUNT(DISTINCT SAL)
                        FROM SCOTT.EMP E2
                        WHERE E1.SAL > E2.SAL) = 1);

-- 14] WAQTDN NUMBER OF EMP'S REPORTING TO EMP WHO IS EARNING 8TH MAX SALARY.
SELECT COUNT(*)
FROM SCOTT.EMP
WHERE MGR IN (SELECT EMPNO
                FROM SCOTT.EMP E1
                WHERE (SELECT COUNT(DISTINCT SAL)
                        FROM SCOTT.EMP E2
                        WHERE E1.SAL > E2.SAL) = 7);

-- 15] WAQTD DNAME OF EMP WHO IS EARNING 12TH MAX SALARY'S MANAGER.
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO 
                FROM SCOTT.EMP E1
                WHERE (SELECT COUNT(DISTINCT SAL)
                        FROM SCOTT.EMP E2
                        WHERE E1.SAL < E2.SAL) = 11);

-- 16] WAQTD LOCATION OF EMP'S WHO ARE THE EMP'S OF A PERSON WHO 
-- IS EARNING 8TH MIN SALARY.
SELECT LOC
FROM SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP E1
                WHERE (SELECT COUNT(DISTINCT SAL)
                        FROM SCOTT.EMP E2
                        WHERE E1.SAL > E2.SAL) = 7);

-- 17] WAQTD MGR'S MGR OF EMP WHO IS EARNING 12TH MAX SALARY.
SELECT ENAME
FROM SCOTT.EMP E1
WHERE EMPNO IN (SELECT MGR
                FROM SCOTT.EMP
                WHERE EMPNO IN (SELECT MGR
                                FROM SCOTT.EMP E1
                                WHERE (SELECT COUNT(DISTINCT SAL)
                                        FROM SCOTT.EMP E2
                                        WHERE E1.SAL < E2.SAL) = 11));

-- 18] WAQTD EMP'S EMP DNAMES IF THEY ARE WORKING UNDER THE EMP
-- WHO IS HAVING 10TH MIN SAL.
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE MGR IN (SELECT EMPNO
                                FROM SCOTT.EMP
                                WHERE MGR IN (SELECT EMPNO
                                                FROM SCOTT.EMP E1
                                                WHERE (SELECT COUNT(DISTINCT SAL)
                                                        FROM SCOTT.EMP E2
                                                        WHERE E1.SAL > E2.SAL) = 9)));

-- 19] WAQTD NUMBER OF EMP'S WHO ARE WORKING IN THE DEPTNO OF
-- EMP WHO IS EARNING 11TH MIN SAL
SELECT COUNT(*)
FROM SCOTT.EMP 
WHERE EXISTS (SELECT DEPTNO
                FROM SCOTT.EMP 
                WHERE EMPNO IN (SELECT EMPNO
                                FROM SCOTT.EMP E1
                                WHERE (SELECT COUNT(DISTINCT SAL)
                                        FROM SCOTT.EMP E2
                                        WHERE E1.SAL > E2.SAL) = 10)) ;

-- 20] WAQTD TOTAL SAL OF EMP'S WHO ARE WORKING THE SAME
-- DESIGNATION AS THAT OF EMP WHO IS EARNING LEAST SALARY.
SELECT SUM(SAL)
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
FROM SCOTT.EMP
WHERE JOB IN (SELECT JOB
                FROM SCOTT.EMP E1
                WHERE (SELECT COUNT(DISTINCT SAL)
                        FROM SCOTT.EMP E2
                        WHERE E1.SAL > E2.SAL) = 0));