-- 1] WAQTD THE DNAME'S IN WHICH EMP'S ARE WORKING.
SELECT DNAME 
FROM SCOTT.DEPT D
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP E
                WHERE E.DEPTNO = D.DEPTNO);

-- 2] WAQTD THE LOCATIO'S WHERE EMP'S ARE PRESENT
SELECT LOC
FROM SCOTT.DEPT D
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP E
                WHERE E.DEPTNO = D.DEPTNO);

-- 3] WAQTD THE DNAME IN WHICH EMP'S ARE NOT WORKING.
SELECT DNAME
FROM SCOTT.DEPT D
WHERE DEPTNO NOT IN (SELECT DEPTNO
                    FROM SCOTT.EMP E
                    WHERE E.DEPTNO = D.DEPTNO);

-- 4] WAQTD THE DIFFERENT DESIGNATIONS IN WHICH EMP'S ARE WORKING
-- IN ALL THE DNAME'S OF DEPT TABLE.
SELECT DISTINCT JOB
FROM SCOTT.DEPT D
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP E
                WHERE E.DEPTNO = D.DEPTNO);