-- 1]WAQTD 2ND MAX SAL IN EACH EACH DEPTN0?
SELECT *
FROM (SELECT SAL, DEPTNO, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK 
        FROM SCOTT.EMP)
WHERE RANK = &N;

-- 2]3RD MAX SAL IN EACH DEPTNO
SELECT *
FROM (SELECT SAL, DEPTNO, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK
        FROM SCOTT.EMP)
WHERE RANK = 3;

-- 3]3RD MIN SAL IN EACH DEPTNO
SELECT *
FROM (SELECT SAL, DEPTNO, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL ASC) AS RANK
        FROM SCOTT.EMP)
WHERE RANK = 3;

DESC SCOTT.EMP;
SELECT *
FROM SCOTT.EMP;

-- 4]WAQTD 2ND MIN SAL IN EACH DEPTNO
SELECT *
FROM (SELECT SAL, DEPTNO, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL) AS RANK
        FROM SCOTT.EMP)
WHERE RANK = 2;

-- 5]WAQTD 2ND MAX SAL IN EACH DESIGNATION
SELECT *
FROM (SELECT SAL, JOB, DENSE_RANK() OVER(PARTITION BY JOB ORDER BY SAL DESC) AS RANK
        FROM SCOTT.EMP)
WHERE RANK = 2;

-- 6]WAQTD 2ND MIN SAL IN EACH DESIGNATION
SELECT *
FROM (SELECT SAL, JOB, DENSE_RANK() OVER(PARTITION BY JOB ORDER BY SAL) AS RANK
        FROM SCOTT.EMP)
WHERE RANK = 2;

-- 7]WAQTD 3RD MAX SAL IN EACH DESIGNATION
SELECT *
FROM (SELECT SAL, JOB, DENSE_RANK() OVER(PARTITION BY JOB ORDER BY SAL DESC) AS RANK
        FROM SCOTT.EMP)
WHERE RANK = 3;

-- 8]WAQTD 3RD MIN SAL IN EACH DESIGNATION
SELECT *
FROM (SELECT SAL, JOB, DENSE_RANK() OVER (PARTITION BY JOB ORDER BY SAL ) AS RANK
        FROM SCOTT.EMP)
        WHERE RANK = 3;

SELECT *
FROM (SELECT SAL, JOB, DENSE_RANK() OVER (PARTITION BY JOB /* EACH DESIGN */ ORDER BY SAL) AS RANK
        FROM EMP )
        WHERE RANK = 3;