SELECT ENAME
FROM SCOTT.EMP
WHERE DEPTNO IN (10, 20);

SELECT SAL, ENAME 
FROM SCOTT.EMP
WHERE DEPTNO NOT IN (10, 30);

SELECT ENAME, HIREDATE
FROM SCOTT.EMP
WHERE JOB IN ('CLERK', 'SALESMAN', 'MANAGER');

SELECT *
FROM SCOTT.EMP
WHERE SAL IN (800, 3000, 2950);

SELECT EMP.*, SAL*12
FROM SCOTT.EMP
WHERE COMM IN (300, 1400, 500);

SELECT ENAME, SAL, SAL*12
FROM SCOTT.EMP
WHERE JOB NOT IN ('SALESMAN', 'MANAGER') AND 
            DEPTNO = 30;

SELECT ENAME, COMM
FROM SCOTT.EMP
WHERE HIREDATE IN ('03-DEC-81', '28-SEP-81');

SELECT *
FROM SCOTT.EMP
WHERE JOB IN ('MANAGER', 'ANALYST') AND 
        DEPTNO != 30;

SELECT *
FROM SCOTT.EMP        
WHERE MGR IN (7902, 7566);