SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME LIKE 'A%';

SELECT ENAME
FROM SCOTT.EMP
WHERE JOB LIKE 'S%';

SELECT *
FROM SCOTT.EMP 
WHERE ENAME LIKE '%T';

SELECT *
FROM SCOTT.EMP
WHERE ENAME LIKE '%A%';

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE '_A%';

SELECT *
FROM SCOTT.EMP
WHERE ENAME LIKE '%A_';

SELECT *
FROM SCOTT.EMP
WHERE ENAME LIKE '%S';

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE '___E%';

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE 'A%S';

SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE SAL LIKE '___';

-- 11
SELECT ENAME, HIREDATE
FROM SCOTT.EMP
WHERE HIREDATE LIKE '%82';  -- '__-___-82' AND '%-%-82'

SELECT *
FROM SCOTT.EMP
WHERE ENAME LIKE 'A%' OR
        ENAME LIKE '%S';

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE 'A%' AND
        DEPTNO IN (10, 20);

SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE SAL LIKE ('____');

SELECT ENAME, HIREDATE 
FROM SCOTT.EMP
WHERE HIREDATE LIKE '%81' AND
        SAL > 2000;

SELECT *
FROM SCOTT.EMP
WHERE JOB LIKE '%MAN%';

SELECT *
FROM SCOTT.EMP
WHERE ENAME LIKE 'AD%S' ;

SELECT ENAME -- ---------------------
FROM SCOTT.EMP
WHERE DEPTNO IN (30, 40) AND
        SAL > 2000;

SELECT *
FROM SCOTT.EMP
WHERE JOB IN ('SALESMAN', 'MANAGER') AND
        DEPTNO = 20 AND 
        HIREDATE LIKE '%83';

SELECT EMP.*, SAL*12
FROM SCOTT.EMP
WHERE SAL*12 > 15000 AND 
        DEPTNO IN (10, 20) AND
        HIREDATE NOT LIKE '%82';