SELECT *
FROM SCOTT.EMP
WHERE SAL < (SELECT SAL
                FROM SCOTT.EMP
                WHERE ENAME = 'KING');

SELECT *
FROM SCOTT.EMP
WHERE JOB IN (SELECT JOB
                FROM SCOTT.EMP
                WHERE ENAME = 'FORD');

SELECT *
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO  
                FROM SCOTT.EMP
                WHERE ENAME = 'KING');

SELECT *
FROM SCOTT.EMP
WHERE HIREDATE > (SELECT HIREDATE 
                    FROM SCOTT.EMP
                    WHERE ENAME IN 'WARD');

SELECT ENAME
FROM SCOTT.EMP
WHERE JOB IN 'SALESMAN' AND
        SAL < (SELECT SAL
                FROM SCOTT.EMP
                WHERE ENAME IN 'MARTIN');

SELECT *
FROM SCOTT.EMP
WHERE SAL > (SELECT SAL
                FROM SCOTT.EMP
                WHERE ENAME IN 'JAMES') AND
        SAL < (SELECT SAL
        FROM SCOTT.EMP
        WHERE ENAME = 'JONES');

SELECT ENAME
FROM SCOTT.EMP
WHERE SAL < (SELECT SAL
                FROM SCOTT.EMP
                WHERE ENAME IN 'KING');

SELECT ENAME 
FROM SCOTT.EMP
WHERE SAL < (SELECT SAL
            FROM SCOTT.EMP
            WHERE ENAME IN 'ADAMS');

SELECT ENAME, DEPTNO
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE ENAME IN 'JONES');

SELECT ENAME, JOB
FROM SCOTT.EMP 
WHERE JOB IN (SELECT JOB
                FROM SCOTT.EMP
                WHERE ENAME IN 'JAMES');

SELECT EMPNO, ENAME , (SAL*12) ANN_SAL
FROM SCOTT.EMP
WHERE SAL*12 >  (SELECT SAL*12
                FROM SCOTT.EMP
                WHERE ENAME IN 'WARD');

SELECT ENAME, HIREDATE
FROM SCOTT.EMP
WHERE HIREDATE < (SELECT HIREDATE
                FROM SCOTT.EMP
                WHERE ENAME IN 'TURNER');


SELECT ENAME, HIREDATE 
FROM SCOTT.EMP
WHERE HIREDATE > (SELECT HIREDATE   
                    FROM SCOTT.EMP
                    WHERE JOB IN 'PRESIDENT');

SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE SAL < (SELECT SAL
                FROM SCOTT.EMP
                WHERE EMPNO IN 7839);

SELECT *
FROM SCOTT.EMP
WHERE HIREDATE < (SELECT HIREDATE       
                FROM SCOTT.EMP
                WHERE ENAME IN 'MILLER');

SELECT *
FROM SCOTT.EMP
WHERE SAL > (SELECT SAL
            FROM SCOTT.EMP
            WHERE ENAME IN 'ALLEN');

SELECT COUNT(*)
FROM SCOTT.EMP
WHERE HIREDATE > (SELECT HIREDATE 
                    FROM SCOTT.EMP
                    WHERE ENAME IN 'KING');

SELECT SUM(SAL)
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE ENAME IN 'WARD');


SELECT *
FROM SCOTT.EMP
WHERE DEPTNO IN 20 AND
        JOB IN (SELECT JOB
                FROM SCOTT.EMP
                WHERE ENAME IN 'SMITH');

SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE SAL BETWEEN (SELECT SAL+1
                    FROM SCOTT.EMP 
                    WHERE ENAME IN 'MILLER') AND 
                    (SELECT SAL-1
                    FROM SCOTT.EMP
                    WHERE ENAME IN 'ALLEN');

SELECT ENAME , SAL
FROM SCOTT.EMP
WHERE SAL BETWEEN 1001 AND 2999;

SELECT *
FROM SCOTT.EMP
WHERE DEPTNO IN 20 AND
        JOB IN (SELECT JOB 
                FROM SCOTT.EMP
                WHERE ENAME IN 'SMITH');

SELECT *
FROM SCOTT.EMP
WHERE JOB IN 'MANAGER' AND
        DEPTNO IN (SELECT DEPTNO
                    FROM SCOTT.EMP
                    WHERE ENAME IN 'TURNER');

SELECT ENAME, HIREDATE 
FROM SCOTT.EMP
WHERE HIREDATE BETWEEN '01-JAN-81' AND
                    (SELECT HIREDATE-1
                    FROM SCOTT.EMP
                    WHERE ENAME IN 'KING' );

SELECT ENAME ,SAL , (SAL*12) ANN_SAL
FROM SCOTT.EMP
WHERE SAL < (SELECT SAL
            FROM SCOTT.EMP
            WHERE ENAME IN 'BLAKE') OR 
            SAL > 3500;