--1 WAQTD DETAILS OF EMP HIIRED ON MONDAY OR FRIDAY OR SATURDAY
SELECT EMP.*, TO_CHAR(HIREDATE, 'DAY')
FROM SCOTT.EMP
WHERE TO_CHAR(HIREDATE, 'D') IN (2, 6, 7);

--2 WAQTD DETAILS OF EMPS WHOSE NAME STARTS WITH VOWELS
SELECT *
FROM SCOTT.EMP 
WHERE SUBSTR(ENAME, 1,1) IN ('A', 'E', 'I', 'O', 'U');

-- 3 DETAILS OF EMP WHO WAS HIRED IN EVEN DATES
SELECT *
FROM SCOTT.EMP
WHERE MOD(TO_NUMBER(TO_CHAR(hiredate, 'DD')), 2) = 0;

-- 4 DETAILS OS EMP HIRED ON ODD DATES
SELECT *
FROM SCOTT.EMP
WHERE MOD(TO_NUMBER(TO_CHAR(HIREDATE, 'DD')), 2) != 0;

-- 5 DISPLAY EVEN NUMBER OF RECORDS
SELECT *
FROM (SELECT ROWNUM AS SLNO, EMP.*
        FROM SCOTT.EMP) 
WHERE MOD(SLNO, 2) = 0;

-- 6 DISPLAY ODD NUMBER OF RECORDS
SELECT *
FROM (SELECT ROWNUM AS SLNO, EMP.*
        FROM SCOTT.EMP) 
WHERE MOD(SLNO, 2) != 0;

-- 7 * OF TOP 2 SALARY HOLDERS
SELECT *
FROM SCOTT.EMP
WHERE SAL IN (SELECT SAL
                FROM (SELECT ROWNUM AS SLNO, SAL
                        FROM (SELECT DISTINCT SAL
                                FROM SCOTT.EMP
                                ORDER BY SAL DESC))
            WHERE SLNO IN (1,2));

--8 SAL OF BOTTOM TWO EMPS
SELECT *
FROM SCOTT.EMP
WHERE SAL IN (SELECT SAL
                FROM (SELECT ROWNUM AS SLNO, SAL
                        FROM (SELECT DISTINCT SAL
                                FROM SCOTT.EMP
                                ORDER BY SAL))
            WHERE SLNO IN (1,2));

-- 9 WAQTD * OF EMP WHO'S NAME ENDS WITH CONSONENTS
SELECT *
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, -1,1) NOT IN ('A', 'E', 'I', 'O', 'U');

--10 * OF EMP WHOS NAMES IS HAVING VOWELS AT THE 3RD PLACE
SELECT *
FROM SCOTT.EMP
WHERE SUBSTR(ENAME, 3,1) IN ('A', 'E', 'I', 'O', 'U');

--11 * OF EMP HIRED ON EVEN MONTH
SELECT*
FROM SCOTT.EMP
WHERE MOD(TO_NUMBER(TO_CHAR(HIREDATE, 'MM')), 2) = 0;

--12 * OF EMP HIRED ON ODD MONTH
SELECT * 
FROM SCOTT.EMP
WHERE MOD(TO_NUMBER(TO_CHAR(HIREDATE, 'MM')), 2) !=0;

-- 13 * OF EMP WHO IS HAVING EVEN LENGTH ON DESIGNATION 
SELECT *
FROM SCOTT.EMP
WHERE MOD(LENGTH(JOB), 2) = 0;

-- 14 * OF EMP WHO IS HAVING ODD LENGTH ON DESIGNATION 
SELECT *
FROM SCOTT.EMP
WHERE MOD(LENGTH(JOB), 2) != 0;

--15 EVEN DAY LENGTH 
SELECT *
FROM SCOTT.EMP
WHERE MOD(LENGTH(TRIM(TO_CHAR(HIREDATE,'DAY'))), 2) = 0;

--16 ODD DAY LENGTH
SELECT *
FROM SCOTT.EMP
WHERE MOD(LENGTH(TRIM(TO_CHAR(HIREDATE,'DAY'))), 2) != 0;

--17 EVEN MONTH LENGTH 
SELECT EMP.*, TO_CHAR(HIREDATE,'MONTH'), LENGTH(TRIM(TO_CHAR(HIREDATE,'MONTH')))
FROM SCOTT.EMP
WHERE MOD(LENGTH(TRIM(TO_CHAR(HIREDATE,'MONTH'))), 2) = 0;

--18 ODD MONTH LENGTH
SELECT EMP.*, TO_CHAR(HIREDATE,'MONTH'), LENGTH(TRIM(TO_CHAR(HIREDATE,'MONTH')))
FROM SCOTT.EMP
WHERE MOD(LENGTH(TRIM(TO_CHAR(HIREDATE,'MONTH'))), 2) != 0;

--19 WAQTD DELETE ANY NTH RECORD
DELETE
FROM SALGRADE
WHERE ROWID IN (SELECT ID
                FROM (SELECT ROWID AS SLNO, ROWID ID, SALGRADE.*
                        FROM SCALGRADE)
                        WHERE SLNO = &N);